// flow-typed signature: 838312f7c401dc71ef0b8d77b0884aa5
// flow-typed version: <<STUB>>/epoch-timeago_v^1.1.9/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'epoch-timeago'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'epoch-timeago' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'epoch-timeago/dist/index' {
  declare module.exports: any;
}

declare module 'epoch-timeago/es/index' {
  declare module.exports: any;
}

declare module 'epoch-timeago/lib/index' {
  declare module.exports: any;
}

declare module 'epoch-timeago/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'epoch-timeago/dist/index.js' {
  declare module.exports: $Exports<'epoch-timeago/dist/index'>;
}
declare module 'epoch-timeago/es/index.js' {
  declare module.exports: $Exports<'epoch-timeago/es/index'>;
}
declare module 'epoch-timeago/lib/index.js' {
  declare module.exports: $Exports<'epoch-timeago/lib/index'>;
}
declare module 'epoch-timeago/src/index.js' {
  declare module.exports: $Exports<'epoch-timeago/src/index'>;
}
